import {useEffect, useState} from 'react';
import {useTranslation} from 'react-i18next';
import {ListIncomingForeignKeys} from '../lib/tabApi';
import {copyToClipboard} from '../lib/gridCopyFormats';
import type {db} from '../../wailsjs/go/models';

interface Props {
    open: boolean;
    tabId: string;
    schema: string;
    table: string;
    statements: string[];
    hasDeletes: boolean;
    executing: boolean;
    error: string | null;
    onClose: () => void;
    onDiscard: () => void;
    onExecute: () => void;
}

// Painel de revisão do script gerado a partir das linhas de rascunho
// (INSERT) e das marcações de exclusão (DELETE) do ResultGrid. O SQL
// exibido é só preview textual (literais formatados) — a execução real
// vai parametrizada via ExecuteBatch no backend.
export default function PendingChangesReview({
    open,
    tabId,
    schema,
    table,
    statements,
    hasDeletes,
    executing,
    error,
    onClose,
    onDiscard,
    onExecute,
}: Props) {
    const {t} = useTranslation();
    const [cascadeFks, setCascadeFks] = useState<db.IncomingForeignKey[]>([]);
    const [cascadeAck, setCascadeAck] = useState(false);
    const [fkError, setFkError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    useEffect(() => {
        if (!open) {
            setCascadeFks([]);
            setCascadeAck(false);
            setFkError(null);
            setCopied(false);
            return;
        }
        if (!hasDeletes) {
            setCascadeFks([]);
            setCascadeAck(false);
            setFkError(null);
            return;
        }
        let cancelled = false;
        setFkError(null);
        setCascadeAck(false);
        void ListIncomingForeignKeys(tabId, schema, table)
            .then(fks => {
                if (cancelled) return;
                setCascadeFks(fks.filter(fk => fk.OnDelete === 'CASCADE'));
            })
            .catch(err => {
                if (cancelled) return;
                setFkError(String(err));
                setCascadeFks([]);
            });
        return () => {
            cancelled = true;
        };
    }, [open, hasDeletes, tabId, schema, table]);

    if (!open) return null;

    const script = statements.join(';\n');
    const needsCascadeAck = cascadeFks.length > 0;
    const canExecute = !executing && (!needsCascadeAck || cascadeAck) && statements.length > 0;

    async function handleCopy() {
        const ok = await copyToClipboard(script);
        if (ok) {
            setCopied(true);
            window.setTimeout(() => setCopied(false), 1500);
        }
    }

    return (
        <div className="grid-edit-overlay" onMouseDown={e => { if (e.target === e.currentTarget && !executing) onClose(); }}>
            <div className="grid-edit-popover pending-changes-review" role="dialog" aria-label={t('resultGrid.reviewChangesAria')}>
                <div className="grid-context-menu-group-label">{t('resultGrid.reviewChangesTitle')}</div>
                <div className="pending-changes-banner">{t('resultGrid.scriptAutoGenerated')}</div>
                <code className="grid-edit-preview pending-changes-script">{script || t('resultGrid.noPendingStatements')}</code>

                {fkError && <div className="insert-form-error">{fkError}</div>}

                {needsCascadeAck && (
                    <div className="pending-changes-cascade">
                        <div className="pending-changes-cascade-title">{t('resultGrid.cascadeWarning')}</div>
                        <ul className="pending-changes-cascade-list">
                            {cascadeFks.map(fk => (
                                <li key={`${fk.FromSchema}.${fk.FromTable}.${fk.Name}`}>
                                    {fk.FromSchema}.{fk.FromTable} ({fk.FromColumns.join(', ')}) → ON DELETE CASCADE
                                </li>
                            ))}
                        </ul>
                        <label className="pending-changes-cascade-ack">
                            <input
                                type="checkbox"
                                checked={cascadeAck}
                                onChange={e => setCascadeAck(e.target.checked)}
                                disabled={executing}
                            />
                            <span>{t('resultGrid.cascadeUnderstand')}</span>
                        </label>
                    </div>
                )}

                {error && <div className="insert-form-error">{error}</div>}

                <div className="grid-edit-actions pending-changes-actions">
                    <button className="btn btn-secondary" onClick={onDiscard} disabled={executing}>
                        {t('resultGrid.discardChanges')}
                    </button>
                    <button className="btn btn-secondary" onClick={() => void handleCopy()} disabled={statements.length === 0 || executing}>
                        {copied ? t('resultGrid.copied') : t('resultGrid.copy')}
                    </button>
                    <button className="btn btn-success" onClick={onExecute} disabled={!canExecute}>
                        {executing ? t('resultGrid.executing') : t('resultGrid.execute')}
                    </button>
                    <button className="btn btn-secondary" onClick={onClose} disabled={executing}>
                        {t('resultGrid.cancel')}
                    </button>
                </div>
            </div>
        </div>
    );
}
