// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectSaved(arg1, arg2) {
  return window['go']['main']['App']['ConnectSaved'](arg1, arg2);
}

export function DeleteRow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteRow'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExecuteBatch(arg1, arg2) {
  return window['go']['main']['App']['ExecuteBatch'](arg1, arg2);
}

export function FetchRows(arg1, arg2) {
  return window['go']['main']['App']['FetchRows'](arg1, arg2);
}

export function GetQueryHistory(arg1) {
  return window['go']['main']['App']['GetQueryHistory'](arg1);
}

export function GetTableDDL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableDDL'](arg1, arg2, arg3);
}

export function InsertRow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3, arg4, arg5);
}

export function IntrospectSchemaTables(arg1, arg2) {
  return window['go']['main']['App']['IntrospectSchemaTables'](arg1, arg2);
}

export function IntrospectTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['IntrospectTable'](arg1, arg2, arg3);
}

export function ListForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListForeignKeys'](arg1, arg2, arg3);
}

export function ListFunctions(arg1, arg2) {
  return window['go']['main']['App']['ListFunctions'](arg1, arg2);
}

export function ListIncomingForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListIncomingForeignKeys'](arg1, arg2, arg3);
}

export function ListIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListIndexes'](arg1, arg2, arg3);
}

export function ListSavedConnections() {
  return window['go']['main']['App']['ListSavedConnections']();
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListScripts() {
  return window['go']['main']['App']['ListScripts']();
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function ListTriggers(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTriggers'](arg1, arg2, arg3);
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function PickSQLiteFile() {
  return window['go']['main']['App']['PickSQLiteFile']();
}

export function RefreshSchema(arg1) {
  return window['go']['main']['App']['RefreshSchema'](arg1);
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['App']['RunQuery'](arg1, arg2);
}

export function SaveConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2, arg3);
}

export function SaveScript(arg1, arg2) {
  return window['go']['main']['App']['SaveScript'](arg1, arg2);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function UpdateCell(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateCell'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2, arg3);
}
