// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function ConnectSaved(arg1, arg2) {
  return window['go']['main']['App']['ConnectSaved'](arg1, arg2);
}

export function DeleteSavedConnection(arg1) {
  return window['go']['main']['App']['DeleteSavedConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function Execute(arg1, arg2) {
  return window['go']['main']['App']['Execute'](arg1, arg2);
}

export function GetQueryHistory(arg1) {
  return window['go']['main']['App']['GetQueryHistory'](arg1);
}

export function ListSavedConnections() {
  return window['go']['main']['App']['ListSavedConnections']();
}

export function ListSchemas(arg1) {
  return window['go']['main']['App']['ListSchemas'](arg1);
}

export function ListTables(arg1, arg2) {
  return window['go']['main']['App']['ListTables'](arg1, arg2);
}

export function RefreshSchema(arg1) {
  return window['go']['main']['App']['RefreshSchema'](arg1);
}

export function SaveConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2, arg3);
}
