// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';
import {store} from '../models';

export function CancelQuery(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ConfirmQuit():Promise<void>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ConnectSaved(arg1:string,arg2:string):Promise<void>;

export function DeleteRow(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<any>):Promise<number>;

export function DeleteSavedConnection(arg1:string):Promise<void>;

export function DeleteScript(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ExecuteBatch(arg1:string,arg2:Array<db.BatchOp>):Promise<void>;

export function FetchRows(arg1:string,arg2:number):Promise<main.FetchBatch>;

export function GetConnectionForEdit(arg1:string):Promise<store.SavedConnectionEdit>;

export function GetQueryHistory(arg1:number):Promise<Array<store.QueryHistoryEntry>>;

export function GetTableDDL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function InsertRow(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<any>):Promise<void>;

export function IntrospectSchemaTables(arg1:string,arg2:string):Promise<Array<db.Table>>;

export function IntrospectTable(arg1:string,arg2:string,arg3:string):Promise<db.Table>;

export function ListForeignKeys(arg1:string,arg2:string,arg3:string):Promise<Array<db.ForeignKey>>;

export function ListFunctions(arg1:string,arg2:string):Promise<Array<db.Function>>;

export function ListIncomingForeignKeys(arg1:string,arg2:string,arg3:string):Promise<Array<db.IncomingForeignKey>>;

export function ListIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<db.Index>>;

export function ListSavedConnections():Promise<Array<store.SavedConnection>>;

export function ListSchemas(arg1:string):Promise<Array<string>>;

export function ListScripts():Promise<Array<store.SavedScript>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<db.Table>>;

export function ListTriggers(arg1:string,arg2:string,arg3:string):Promise<Array<db.Trigger>>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function PickSQLiteFile():Promise<string>;

export function RefreshSchema(arg1:string):Promise<void>;

export function ReportFrontendError(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunQuery(arg1:string,arg2:string):Promise<main.QueryMetadata>;

export function SaveConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveScript(arg1:string,arg2:string):Promise<string>;

export function TestConnection(arg1:string,arg2:string):Promise<void>;

export function UpdateCell(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<any>,arg6:string,arg7:any,arg8:any):Promise<number>;

export function UpdateScript(arg1:string,arg2:string,arg3:string):Promise<void>;
